#
# Travis Setup
#

# build only on master branches
# commented as this prevents people from running builds on their forks:
# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
#branches:
#  only:
#    - master
#    - 3.0


#
# Test Matrix
#

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  code_climate:
    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: nightly

  allow_failures:
    - php: nightly

before_install:
  # Always remove xdebug.
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
install:
  # install composer dependencies
  - travis_retry composer self-update
  # Fast composer install
  - travis_retry composer global require hirak/prestissimo
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version
script:
  # PHP tests
  - vendor/bin/phpunit
